const PETS = [
  {
    id: "A001",
    name: "Luna",
    species: "Dog",
    breed: "Labrador Retriever Mix",
    size: "68lbs",
    age: "3 years old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1537204696486-967f1b7198c8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFicmFkb3J8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Luna is a sweet and energetic girl who loves fetch and long walks. She's well-trained and knows basic commands. Would make a perfect companion for an active family.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Sarah Mitchell",
    date_arrived_shelter: "2025-08-15",
    date_in_transit: "2025-08-20",
    date_arrived_foster: "2025-08-22",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A002",
    name: "Whiskers",
    species: "Cat",
    breed: "Domestic Shorthair",
    size: "8lbs",
    age: "5 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Whiskers is a laid-back gentleman who enjoys sunbathing and quiet afternoons. He's independent but loves attention on his own terms. Perfect for a calm household.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: true,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-01",
    date_in_transit: "2025-09-05",
    date_arrived_foster: "2025-09-06",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: true,
  },
  {
    id: "A003",
    name: "Buddy",
    species: "Dog",
    breed: "German Shepherd",
    size: "72lbs",
    age: "4 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Z2VybWFuJTIwc2hlcGhlcmQlMjBkb2d8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Buddy is a loyal and protective companion who bonds deeply with his family. He's intelligent and eager to please, with excellent guarding instincts.",
    special_needs: "Requires experienced handler",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Amanda Rodriguez",
    date_arrived_shelter: "2025-07-10",
    date_in_transit: "2025-07-15",
    date_arrived_foster: "2025-07-16",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A004",
    name: "Mittens",
    species: "Cat",
    breed: "Siamese Mix",
    size: "4lbs",
    age: "2 months old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2F0fGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Mittens is a playful and vocal kitty who loves to chat with her humans. She's curious and affectionate, always ready for playtime or cuddles.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-06-20",
    date_in_transit: "2025-06-25",
    date_arrived_foster: "2025-06-26",
    date_adopted: "2025-09-10",
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A005",
    name: "Max",
    species: "Dog",
    breed: "Beagle",
    size: "37lbs",
    age: "6 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmVhZ2xlfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Max is a sweet senior boy with a gentle soul. He enjoys leisurely walks and plenty of naps. He's great with everyone and just wants to be loved.",
    special_needs: "Arthritis medication required",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Patricia Williams",
    date_arrived_shelter: "2025-08-01",
    date_in_transit: "2025-08-10",
    date_arrived_foster: "2025-08-12",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A006",
    name: "Shadow",
    species: "Cat",
    breed: "Black Domestic Longhair",
    size: "12lbs",
    age: "7 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1628363430169-9552e356d8ea?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGxvbmdoYWlyJTIwYmxhY2slMjBjYXR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Shadow is a majestic black cat with a luxurious coat. He's calm and affectionate, enjoying quiet companionship and gentle pets.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-20",
    date_in_transit: "2025-09-25",
    date_arrived_foster: "2025-09-26",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A007",
    name: "Bella",
    species: "Dog",
    breed: "Pit Bull Terrier Mix",
    size: "21lbs",
    age: "5 months old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1455103493930-a116f655b6c5?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGl0YnVsbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Bella is a bouncy, lovable girl with endless enthusiasm. She's great with people and loves to play. Her happy personality is contagious!",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "James Peterson",
    date_arrived_shelter: "2025-09-15",
    date_in_transit: "2025-09-20",
    date_arrived_foster: "2025-09-21",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A008",
    name: "Oliver",
    species: "Cat",
    breed: "Orange Tabby",
    size: "7lbs",
    age: "1 year old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8a2l0dGVufGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Oliver is a young, energetic kitten who loves to explore. He's playful and social, getting along well with other cats and children.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-01",
    date_in_transit: "2025-10-05",
    date_arrived_foster: "2025-10-06",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: true,
  },
];

export default PETS;
