const PETS = [
  {
    id: "A001",
    name: "Luna",
    species: "Dog",
    breed: "Labrador Retriever Mix",
    size: "68lbs",
    age: "3 years old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1537204696486-967f1b7198c8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFicmFkb3J8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Luna is a sweet and energetic girl who loves fetch and long walks. She's well-trained and knows basic commands. Would make a perfect companion for an active family.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Sarah Mitchell",
    date_arrived_shelter: "2025-08-15",
    date_in_transit: "2025-08-20",
    date_arrived_foster: "2025-08-22",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A002",
    name: "Whiskers",
    species: "Cat",
    breed: "Domestic Shorthair",
    size: "8lbs",
    age: "5 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Whiskers is a laid-back gentleman who enjoys sunbathing and quiet afternoons. He's independent but loves attention on his own terms. Perfect for a calm household.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: true,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-01",
    date_in_transit: "2025-09-05",
    date_arrived_foster: "2025-09-06",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: true,
  },
  {
    id: "A003",
    name: "Buddy",
    species: "Dog",
    breed: "German Shepherd",
    size: "72lbs",
    age: "4 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Z2VybWFuJTIwc2hlcGhlcmQlMjBkb2d8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Buddy is a loyal and protective companion who bonds deeply with his family. He's intelligent and eager to please, with excellent guarding instincts.",
    special_needs: "Requires experienced handler",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Amanda Rodriguez",
    date_arrived_shelter: "2025-07-10",
    date_in_transit: "2025-07-15",
    date_arrived_foster: "2025-07-16",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A004",
    name: "Mittens",
    species: "Cat",
    breed: "Siamese Mix",
    size: "4lbs",
    age: "2 months old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2F0fGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Mittens is a playful and vocal kitty who loves to chat with her humans. She's curious and affectionate, always ready for playtime or cuddles.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-06-20",
    date_in_transit: "2025-06-25",
    date_arrived_foster: "2025-06-26",
    date_adopted: "2025-09-10",
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A005",
    name: "Max",
    species: "Dog",
    breed: "Beagle",
    size: "37lbs",
    age: "6 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmVhZ2xlfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Max is a sweet senior boy with a gentle soul. He enjoys leisurely walks and plenty of naps. He's great with everyone and just wants to be loved.",
    special_needs: "Arthritis medication required",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Patricia Williams",
    date_arrived_shelter: "2025-08-01",
    date_in_transit: "2025-08-10",
    date_arrived_foster: "2025-08-12",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A006",
    name: "Shadow",
    species: "Cat",
    breed: "Black Domestic Longhair",
    size: "12lbs",
    age: "7 years old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1628363430169-9552e356d8ea?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGxvbmdoYWlyJTIwYmxhY2slMjBjYXR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Shadow is a majestic black cat with a luxurious coat. He's calm and affectionate, enjoying quiet companionship and gentle pets.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-20",
    date_in_transit: "2025-09-25",
    date_arrived_foster: "2025-09-26",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A007",
    name: "Bella",
    species: "Dog",
    breed: "Pit Bull Terrier Mix",
    size: "21lbs",
    age: "5 months old",
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1455103493930-a116f655b6c5?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGl0YnVsbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    description:
      "Bella is a bouncy, lovable girl with endless enthusiasm. She's great with people and loves to play. Her happy personality is contagious!",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "James Peterson",
    date_arrived_shelter: "2025-09-15",
    date_in_transit: "2025-09-20",
    date_arrived_foster: "2025-09-21",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A008",
    name: "Oliver",
    species: "Cat",
    breed: "Orange Tabby",
    size: "7lbs",
    age: "1 year old",
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8a2l0dGVufGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    description:
      "Oliver is a young, energetic kitten who loves to explore. He's playful and social, getting along well with other cats and children.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-01",
    date_in_transit: "2025-10-05",
    date_arrived_foster: "2025-10-06",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: true,
  },
  {
    id: "A009",
    name: "Rocky",
    species: "Dog",
    breed: "Boxer Mix",
    size: "Large",
    age: 5,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1594118319842-b72837a0ecea?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Rocky is a gentle giant with a heart of gold. Despite his size, he's very gentle and loves children. He's house-trained and well-behaved.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Maria Garcia",
    date_arrived_shelter: "2025-08-25",
    date_in_transit: "2025-09-01",
    date_arrived_foster: "2025-09-02",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A010",
    name: "Cleo",
    species: "Cat",
    breed: "Calico",
    size: "Small",
    age: 8,
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1583417083471-223da5a9f68c?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Cleo is a sophisticated lady who prefers a quiet home. She's affectionate with her chosen people and enjoys being the center of attention.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Linda Taylor",
    date_arrived_shelter: "2025-07-05",
    date_in_transit: "2025-07-10",
    date_arrived_foster: "2025-07-11",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A011",
    name: "Charlie",
    species: "Dog",
    breed: "Golden Retriever",
    size: "Large",
    age: 8,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1581285217236-a2355291f9c9?q=80&w=830&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Charlie is a wonderful senior dog with impeccable manners. He's calm, loving, and perfect for someone looking for a laid-back companion.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Thomas Brown",
    date_arrived_shelter: "2025-05-10",
    date_in_transit: "2025-05-15",
    date_arrived_foster: "2025-05-16",
    date_adopted: "2025-08-20",
    adoption_coordinator: "David Kim",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A012",
    name: "Pumpkin",
    species: "Cat",
    breed: "Orange Domestic Shorthair",
    size: "Medium",
    age: 3,
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1702701752458-19366f87fad8?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Pumpkin is a sweet girl with a gentle nature. She loves being brushed and will purr contentedly for hours. Very easy-going and adaptable.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-10",
    date_in_transit: "2025-10-14",
    date_arrived_foster: "2025-10-15",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A013",
    name: "Duke",
    species: "Dog",
    breed: "Rottweiler",
    size: "Large",
    age: 3,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1669109947479-728a0d33b9b2?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Duke is a loyal protector who needs an experienced owner. He's intelligent and trainable, with strong guardian instincts.",
    special_needs: "Requires experienced handler",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Shelter",
    shelter_name: "Happy Paws Animal Shelter",
    transit_partner: null,
    foster_name: null,
    date_arrived_shelter: "2025-10-25",
    date_in_transit: null,
    date_arrived_foster: null,
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A014",
    name: "Luna",
    species: "Cat",
    breed: "Tuxedo Cat",
    size: "Medium",
    age: 4,
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1695390838800-ee7886efb253?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Luna is an elegant tuxedo cat with a playful spirit. She enjoys interactive toys and will entertain you with her antics.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-05",
    date_in_transit: "2025-09-10",
    date_arrived_foster: "2025-09-11",
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A015",
    name: "Sadie",
    species: "Dog",
    breed: "Australian Shepherd Mix",
    size: "Medium",
    age: 2,
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1728448644168-cc623aca8256?q=80&w=770&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Sadie is an energetic and intelligent girl who needs plenty of mental and physical stimulation. She'd be perfect for an active family.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Karen Martinez",
    date_arrived_shelter: "2025-09-25",
    date_in_transit: "2025-09-30",
    date_arrived_foster: "2025-10-01",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A016",
    name: "Milo",
    species: "Cat",
    breed: "Gray Tabby",
    size: "Medium",
    age: 6,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1739553622517-0c6ae935b091?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Milo is a handsome tabby with a calm demeanor. He's great with other cats and enjoys a peaceful environment.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: true,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Transit",
    shelter_name: "Happy Paws Animal Shelter",
    transit_partner: "Paws in Transit - Cats",
    foster_name: null,
    date_arrived_shelter: "2025-10-20",
    date_in_transit: "2025-11-01",
    date_arrived_foster: null,
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A017",
    name: "Zeus",
    species: "Dog",
    breed: "Great Dane",
    size: "Extra Large",
    age: 4,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1676290724711-bd092072a9c4?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Zeus is a gentle giant who thinks he's a lap dog. Despite his enormous size, he's very sweet and loves to snuggle.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Daniel White",
    date_arrived_shelter: "2025-08-05",
    date_in_transit: "2025-08-12",
    date_arrived_foster: "2025-08-13",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A018",
    name: "Simba",
    species: "Cat",
    breed: "Maine Coon Mix",
    size: "Large",
    age: 5,
    sex: "Male",
    image_link:
      "https://images.unsplash.com/photo-1591696038577-944232f59007?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Simba is a magnificent cat with a luxurious mane. He's friendly and outgoing, greeting everyone who visits with a chirp.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-07-01",
    date_in_transit: "2025-07-05",
    date_arrived_foster: "2025-07-06",
    date_adopted: "2025-10-15",
    adoption_coordinator: "Rachel Green",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A019",
    name: "Daisy",
    species: "Dog",
    breed: "Chihuahua Mix",
    size: "Small",
    age: 3,
    sex: "Female",
    image_link:
      "https://images.unsplash.com/photo-1558349359-c00462b97aee?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Daisy is a tiny girl with a big personality. She's affectionate with her people but can be shy with strangers initially.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Nancy Lee",
    date_arrived_shelter: "2025-09-12",
    date_in_transit: "2025-09-18",
    date_arrived_foster: "2025-09-19",
    date_adopted: null,
    adoption_coordinator: "Emily White",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A020",
    name: "Pepper",
    species: "Cat",
    breed: "Black and White Domestic Shorthair",
    size: "Medium",
    age: 2,
    sex: "Female",
    image_link: "placeholder_cat_010.jpg",
    description:
      "Pepper is a playful young cat who loves to chase toys and explore. She's friendly and would do well in most homes.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-08",
    date_in_transit: "2025-10-12",
    date_arrived_foster: "2025-10-13",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A021",
    name: "Cooper",
    species: "Dog",
    breed: "Border Collie",
    size: "Medium",
    age: 1,
    sex: "Male",
    image_link: "placeholder_dog_011.jpg",
    description:
      "Cooper is an incredibly smart puppy who needs lots of training and exercise. He's quick to learn and eager to please.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Kevin Anderson",
    date_arrived_shelter: "2025-10-15",
    date_in_transit: "2025-10-20",
    date_arrived_foster: "2025-10-21",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: true,
  },
  {
    id: "A022",
    name: "Ginger",
    species: "Cat",
    breed: "Orange Persian Mix",
    size: "Medium",
    age: 4,
    sex: "Female",
    image_link: "placeholder_cat_011.jpg",
    description:
      "Ginger is a beautiful fluffy cat who requires regular grooming. She's sweet-natured and enjoys being pampered.",
    special_needs: "Requires regular grooming",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Susan Clark",
    date_arrived_shelter: "2025-08-18",
    date_in_transit: "2025-08-22",
    date_arrived_foster: "2025-08-23",
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A023",
    name: "Toby",
    species: "Dog",
    breed: "Cocker Spaniel",
    size: "Medium",
    age: 7,
    sex: "Male",
    image_link: "placeholder_dog_012.jpg",
    description:
      "Toby is a sweet senior boy with lots of love to give. He enjoys gentle walks and plenty of belly rubs. Perfect for a quiet home.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Patricia Williams",
    date_arrived_shelter: "2025-09-08",
    date_in_transit: "2025-09-14",
    date_arrived_foster: "2025-09-15",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A025",
    name: "Ruby",
    species: "Dog",
    breed: "Dachshund",
    size: "Small",
    age: 5,
    sex: "Female",
    image_link: "placeholder_dog_013.jpg",
    description:
      "Ruby is a spunky little dog with a lot of personality. She's playful and loves to burrow under blankets for naps.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Michelle Johnson",
    date_arrived_shelter: "2025-10-05",
    date_in_transit: "2025-10-10",
    date_arrived_foster: "2025-10-11",
    date_adopted: null,
    adoption_coordinator: "Emily White",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A026",
    name: "Felix",
    species: "Cat",
    breed: "Tuxedo Cat",
    size: "Medium",
    age: 3,
    sex: "Male",
    image_link: "placeholder_cat_013.jpg",
    description:
      "Felix is a charming tuxedo cat with excellent manners. He's friendly, well-adjusted, and gets along with everyone.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-09-28",
    date_in_transit: "2025-10-02",
    date_arrived_foster: "2025-10-03",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A027",
    name: "Bear",
    species: "Dog",
    breed: "Newfoundland Mix",
    size: "Extra Large",
    age: 6,
    sex: "Male",
    image_link: "placeholder_dog_014.jpg",
    description:
      "Bear is a gentle giant who loves water and children. He's calm, patient, and makes an excellent family companion.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Christopher Moore",
    date_arrived_shelter: "2025-06-01",
    date_in_transit: "2025-06-08",
    date_arrived_foster: "2025-06-09",
    date_adopted: "2025-09-25",
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A028",
    name: "Nala",
    species: "Cat",
    breed: "Tortoiseshell",
    size: "Small",
    age: 6,
    sex: "Female",
    image_link: "placeholder_cat_014.jpg",
    description:
      "Nala is a petite tortie with a sassy attitude. She knows what she wants and isn't afraid to tell you. Very entertaining!",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Susan Clark",
    date_arrived_shelter: "2025-09-18",
    date_in_transit: "2025-09-22",
    date_arrived_foster: "2025-09-23",
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A029",
    name: "Tucker",
    species: "Dog",
    breed: "Yorkshire Terrier",
    size: "Small",
    age: 4,
    sex: "Male",
    image_link: "placeholder_dog_015.jpg",
    description:
      "Tucker is a confident little guy with a big dog personality. He's energetic and loves to be the center of attention.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Nancy Lee",
    date_arrived_shelter: "2025-10-12",
    date_in_transit: "2025-10-17",
    date_arrived_foster: "2025-10-18",
    date_adopted: null,
    adoption_coordinator: "Emily White",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A030",
    name: "Bella",
    species: "Cat",
    breed: "Ragdoll Mix",
    size: "Large",
    age: 2,
    sex: "Female",
    image_link: "placeholder_cat_015.jpg",
    description:
      "Bella is a gorgeous, floppy girl who lives up to her Ragdoll heritage. She's extremely affectionate and loves to be held.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-20",
    date_in_transit: "2025-10-24",
    date_arrived_foster: "2025-10-25",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A031",
    name: "Ace",
    species: "Dog",
    breed: "Husky Mix",
    size: "Large",
    age: 3,
    sex: "Male",
    image_link: "placeholder_dog_016.jpg",
    description:
      "Ace is a high-energy dog who needs an active family. He loves to run and would be perfect for hiking or jogging companions.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Transit",
    shelter_name: "Rescue Haven",
    transit_partner: "Safe Journey Transport",
    foster_name: null,
    date_arrived_shelter: "2025-10-28",
    date_in_transit: "2025-11-05",
    date_arrived_foster: null,
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A032",
    name: "Princess",
    species: "Cat",
    breed: "White Persian",
    size: "Medium",
    age: 5,
    sex: "Female",
    image_link: "placeholder_cat_016.jpg",
    description:
      "Princess lives up to her name - she's regal and expects to be treated accordingly. She's sweet but has high maintenance grooming needs.",
    special_needs: "Requires daily grooming",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Susan Clark",
    date_arrived_shelter: "2025-08-08",
    date_in_transit: "2025-08-14",
    date_arrived_foster: "2025-08-15",
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A033",
    name: "Murphy",
    species: "Dog",
    breed: "Irish Setter",
    size: "Large",
    age: 2,
    sex: "Male",
    image_link: "placeholder_dog_017.jpg",
    description:
      "Murphy is a beautiful red setter with boundless energy. He's friendly, goofy, and brings joy wherever he goes.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Brian Harris",
    date_arrived_shelter: "2025-09-22",
    date_in_transit: "2025-09-28",
    date_arrived_foster: "2025-09-29",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A034",
    name: "Boots",
    species: "Cat",
    breed: "Black and White Tuxedo",
    size: "Medium",
    age: 7,
    sex: "Male",
    image_link: "placeholder_cat_017.jpg",
    description:
      "Boots is a distinguished gentleman with white paws that look like boots. He's calm, friendly, and very social.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-05-20",
    date_in_transit: "2025-05-26",
    date_arrived_foster: "2025-05-27",
    date_adopted: "2025-08-05",
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A035",
    name: "Rosie",
    species: "Dog",
    breed: "Corgi Mix",
    size: "Small",
    age: 4,
    sex: "Female",
    image_link: "placeholder_dog_018.jpg",
    description:
      "Rosie is an adorable low-rider with a big smile. She's playful, affectionate, and loves everyone she meets.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Michelle Johnson",
    date_arrived_shelter: "2025-10-01",
    date_in_transit: "2025-10-06",
    date_arrived_foster: "2025-10-07",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: true,
  },
  {
    id: "A036",
    name: "Tigger",
    species: "Cat",
    breed: "Orange Tabby",
    size: "Large",
    age: 1,
    sex: "Male",
    image_link: "placeholder_cat_018.jpg",
    description:
      "Tigger is a bouncy young cat full of energy. He loves to play and would benefit from another playful cat companion.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-22",
    date_in_transit: "2025-10-26",
    date_arrived_foster: "2025-10-27",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A037",
    name: "Hank",
    species: "Dog",
    breed: "Basset Hound",
    size: "Medium",
    age: 8,
    sex: "Male",
    image_link: "placeholder_dog_019.jpg",
    description:
      "Hank is a mellow senior with droopy ears and soulful eyes. He enjoys leisurely sniffing walks and lots of couch time.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Patricia Williams",
    date_arrived_shelter: "2025-08-28",
    date_in_transit: "2025-09-03",
    date_arrived_foster: "2025-09-04",
    date_adopted: null,
    adoption_coordinator: "David Kim",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A038",
    name: "Misty",
    species: "Cat",
    breed: "Gray Russian Blue Mix",
    size: "Medium",
    age: 3,
    sex: "Female",
    image_link: "placeholder_cat_019.jpg",
    description:
      "Misty is a shy but sweet girl who takes time to warm up. Once she trusts you, she's incredibly affectionate.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: true,
    needs_home_without_young_children: true,
    needs_home_without_men: true,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Linda Taylor",
    date_arrived_shelter: "2025-09-10",
    date_in_transit: "2025-09-16",
    date_arrived_foster: "2025-09-17",
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A039",
    name: "Buster",
    species: "Dog",
    breed: "Boston Terrier",
    size: "Small",
    age: 5,
    sex: "Male",
    image_link: "placeholder_dog_020.jpg",
    description:
      "Buster is a fun-loving little clown who makes everyone laugh. He's friendly, playful, and great with kids.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Kevin Anderson",
    date_arrived_shelter: "2025-10-08",
    date_in_transit: "2025-10-14",
    date_arrived_foster: "2025-10-15",
    date_adopted: null,
    adoption_coordinator: "Emily White",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A040",
    name: "Patches",
    species: "Cat",
    breed: "Calico Domestic Shorthair",
    size: "Small",
    age: 10,
    sex: "Female",
    image_link: "placeholder_cat_020.jpg",
    description:
      "Patches is a sweet senior lady looking for a quiet retirement home. She's gentle, loving, and very easy-going.",
    special_needs: "Hyperthyroid medication required",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Shelter",
    shelter_name: "Happy Paws Animal Shelter",
    transit_partner: null,
    foster_name: null,
    date_arrived_shelter: "2025-11-02",
    date_in_transit: null,
    date_arrived_foster: null,
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A041",
    name: "Jake",
    species: "Dog",
    breed: "Pointer Mix",
    size: "Large",
    age: 3,
    sex: "Male",
    image_link: "placeholder_dog_021.jpg",
    description:
      "Jake is an athletic dog who loves outdoor activities. He'd be perfect for a hunting companion or active outdoor enthusiast.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Brian Harris",
    date_arrived_shelter: "2025-09-05",
    date_in_transit: "2025-09-12",
    date_arrived_foster: "2025-09-13",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A042",
    name: "Snowball",
    species: "Cat",
    breed: "White Domestic Longhair",
    size: "Medium",
    age: 4,
    sex: "Female",
    image_link: "placeholder_cat_021.jpg",
    description:
      "Snowball is a fluffy white beauty who loves attention. She's playful and social, enjoying both playtime and cuddles.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Emma Davis",
    date_arrived_shelter: "2025-10-15",
    date_in_transit: "2025-10-19",
    date_arrived_foster: "2025-10-20",
    date_adopted: null,
    adoption_coordinator: "Michael Thompson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A043",
    name: "Tank",
    species: "Dog",
    breed: "English Bulldog",
    size: "Medium",
    age: 6,
    sex: "Male",
    image_link: "placeholder_dog_022.jpg",
    description:
      "Tank is a lovable meatball who enjoys snoring on the couch. He's low-energy and perfect for someone looking for a chill companion.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "Adopted",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Daniel White",
    date_arrived_shelter: "2025-07-15",
    date_in_transit: "2025-07-22",
    date_arrived_foster: "2025-07-23",
    date_adopted: "2025-10-20",
    adoption_coordinator: "David Kim",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A044",
    name: "Socks",
    species: "Cat",
    breed: "Black Cat with White Paws",
    size: "Medium",
    age: 2,
    sex: "Male",
    image_link: "placeholder_cat_022.jpg",
    description:
      "Socks is a handsome boy with distinctive white paws. He's playful, curious, and gets along well with other cats.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Robert Chen",
    date_arrived_shelter: "2025-10-18",
    date_in_transit: "2025-10-22",
    date_arrived_foster: "2025-10-23",
    date_adopted: null,
    adoption_coordinator: "Lisa Anderson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A045",
    name: "Maggie",
    species: "Dog",
    breed: "Springer Spaniel",
    size: "Medium",
    age: 7,
    sex: "Female",
    image_link: "placeholder_dog_023.jpg",
    description:
      "Maggie is a sweet senior girl with a gentle disposition. She loves walks and is well-mannered in the house.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Patricia Williams",
    date_arrived_shelter: "2025-09-20",
    date_in_transit: "2025-09-26",
    date_arrived_foster: "2025-09-27",
    date_adopted: null,
    adoption_coordinator: "Sarah Johnson",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A046",
    name: "Midnight",
    species: "Cat",
    breed: "Black Domestic Shorthair",
    size: "Small",
    age: 5,
    sex: "Female",
    image_link: "placeholder_cat_023.jpg",
    description:
      "Midnight is a sleek black cat with bright green eyes. She's affectionate and loves to follow her people around the house.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: true,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Transit",
    shelter_name: "Rescue Haven",
    transit_partner: "Feline Express",
    foster_name: null,
    date_arrived_shelter: "2025-10-30",
    date_in_transit: "2025-11-06",
    date_arrived_foster: null,
    date_adopted: null,
    adoption_coordinator: "Rachel Green",
    available_for_adoption: false,
    adoption_pending: false,
  },
  {
    id: "A047",
    name: "Ranger",
    species: "Dog",
    breed: "Australian Cattle Dog",
    size: "Medium",
    age: 2,
    sex: "Male",
    image_link: "placeholder_dog_024.jpg",
    description:
      "Ranger is an intelligent and energetic working breed who needs a job to do. Perfect for someone with land or an active lifestyle.",
    special_needs: "None",
    medical_status: "Vaccinated, neutered, microchipped",
    needs_home_without_cats: true,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Brian Harris",
    date_arrived_shelter: "2025-10-10",
    date_in_transit: "2025-10-16",
    date_arrived_foster: "2025-10-17",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
  {
    id: "A048",
    name: "Lily",
    species: "Cat",
    breed: "Cream Tabby",
    size: "Small",
    age: 1,
    sex: "Female",
    image_link: "placeholder_cat_024.jpg",
    description:
      "Lily is a delicate young cat with a sweet temperament. She's gentle and would do well in a quiet home.",
    special_needs: "None",
    medical_status: "Vaccinated, spayed, microchipped",
    needs_home_without_cats: false,
    needs_home_without_dogs: false,
    needs_home_without_young_children: false,
    needs_home_without_men: false,
    status: "In Foster",
    shelter_name: null,
    transit_partner: null,
    foster_name: "Susan Clark",
    date_arrived_shelter: "2025-10-25",
    date_in_transit: "2025-10-29",
    date_arrived_foster: "2025-10-30",
    date_adopted: null,
    adoption_coordinator: "Jennifer Martinez",
    available_for_adoption: true,
    adoption_pending: false,
  },
];

export default PETS;
